project:
  type: website
  output-dir: docs
  
website:
  title: "Baptiste Alglave"
  navbar:
    left:
      - research_interest.qmd
      - teaching_supervision.qmd

  
format:
  html:
    theme: materia
    css: styles.css
    toc: true

# Publishing Jekyll style on github: https://idratherbewriting.com/documentation-theme-jekyll/mydoc_publishing_github_pages.html
# Jekyll styles: https://github.com/topics/jekyll-theme