project:
  type: website
  output-dir: docs
  
website:
  title: "Baptiste Alglave"
  navbar:
    left:
      - research_interest.qmd
      - bio.qmd
      - sci_prod.qmd
      - teaching_supervision.qmd
      - stat_meth.qmd
      - lab_comm.qmd

  
format:
  html:
    theme: materia
    css: styles.css
    toc: true
