project:
  type: website
  output-dir: docs

website:
  title: "Baptiste Alglave"
  navbar:
    background: "#1a4a2e"
    foreground: "white"
    left:
      - research_interest.qmd
      - teaching.qmd
      # - supervision.qmd

format:
  html:
    theme: styles.scss
    toc: true

runs:
  using: 'node20'
  main: 'main.js'