project:
  type: website
  output-dir: docs
  
website:
  title: "Baptiste Alglave"
  navbar:
    background: "#1a3a4a"
    foreground: "white"
    left:
      - research_interest.qmd
      - teaching.qmd
      # - supervision.qmd
    right:
      - text: "CV"
        href: ressource/pdf/cv_baptiste_alglave_short.pdf

body-header: banner.html   # ← add this line

format:
  html:
    theme: styles.scss
    toc: true

runs:
  using: 'node20'
  main: 'main.js'