project:
  type: website
  output-dir: docs
  
website:
  title: "Baptiste Alglave"
  navbar:
    left:
      - href: research_interest.qmd
        text: Research interest
      - bio.qmd
      - sci_prod.qmd
      - contact.qmd

  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
