---
title: "Biography"
editor: visual
---

## **PhD**

2019 - 2022

*Subject:* Inferring fish spatio-temporal distribution and identifying essential habitats: tackling the challenges of heterogeneous data integration, preferential sampling and change of support.

*Institute:* Ifremer and Institut Agro (Rennes) - UMR DECOD

*Supervisors:* Youen Vermard, Marie-Pierre Etienne, Mathieu Woillez, Etienne Rivot.

*Mobility* (August - October 2021): DTU Aqua, Copenhagen, Danemark. Supervision of Kasper Kristensen.

## **MSc**

2018 - 2019

*Major:* Fisheries science and quantitative ecology

*Institute:* Institut Agro (Rennes)

**Master thesis** (February - August 2019)

*Institute:* Ifremer Nantes - EMH Research Unit

*Subject:* Management Strategy Evaluation under stock structure uncertainty. Application to the common sole in the Eastern English Channel.

*Supervisors:* Sigrid Lehuta, Youen Vermard.

## **BSc**

2015 - 2017

*Major:* agriculture, food and environment

*Institutes:* Institut Agro (Rennes), CPGE Janson de Sailly (Paris)

*Mobility* (August - December 2017): semester study at University College Cork, Ireland.
