---
title: "Scientific production"
editor: visual
---

## Scientific publications

#### Peer-reviewed

Alglave, B., Rivot, E., Etienne, M. P., Woillez, M., Thorson, J. T., & Vermard, Y. (2022). **Combining scientific survey and commercial catch data to map fish distribution.** *ICES Journal of Marine Science*, *79*(4), 1133-1149. <a href=https://www.researchgate.net/publication/359083638_Combining_scientific_survey_and_commercial_catch_data_to_map_fish_distribution>link</a>

#### Under review

Alglave Baptiste, Vermard Youen, Rivot Etienne, Etienne Marie-Pierre, Woillez Mathieu (under review). **Identifying reproduction areas from space-time modeling of catch declarations and scientific survey data.** Submitted in the Canadian Journal of Fisheries and Aquatic Sciences. <a href=https://hal.archives-ouvertes.fr/hal-03674691/>link</a>

#### In preparation

Alglave Baptiste, Kristensen Kasper, Vermard Youen, Rivot Etienne, Woillez Mathieu, Etienne Marie-Pierre (in prep). **Downscaling coarse observations to predict continuous wild species spatial distribution.** Expected submission: end September 2022. Link soon available.

Alglave Baptiste, Bez Nicolas, Etienne Marie-Pierre, Grandremy Nina, Vermard Youen, Woillez Mathieu, Rivot Etienne (in prep). **Analysing the main spatio-temporal patterns from species distribution models can help identifying fish essential habitats.** Expected submission: October/November 2022. Link soon available.

## Conference presentations

Alglave Baptiste, Vermard Youen, Bez Nicolas, Etienne Marie-Pierre, Kristensen Kasper, Thorson James T., Woillez Mathieu, Rivot Etienne (2022). **Can we trust commercial catch declarations data to map fish spatio-temporal distribution and identify fish essential habitats?** 15th conference of the AFH \`Fisheries research and sustainable development'. June 2022, Brest, France. <a href=ressource/pdf/afh_2022_alglave.pdf>link</a>

Alglave Baptiste, Vermard Youen, Etienne Marie-Pierre, Woillez Mathieu, Rivot Etienne (2022). **Can we use catch declarations data to map fish spatial distribution?** International Statistical Ecology Conference (ISEC). June 2022, Cape Town, South Africa. <a href=ressource/pdf/isec_2022_alglave.pdf>link</a>

Alglave Baptiste, Kristensen Kasper, Vermard Youen, Rivot Etienne, Woillez Mathieu, Etienne Marie-Pierre (2022). **Downscaling coarse observations to predict continuous species spatio-temporal distribution.** Annual meeting of the RESSTE network 'Spatio-temporal statistics for remote sensing data\`. May 2022, Paris, France. <a href=ressource/pdf/resste_2022_alglave.pdf>link</a>

Alglave Baptiste, Kristensen Kasper, Vermard Youen, Rivot Etienne, Woillez Mathieu, Etienne Marie-Pierre (2022). **Going from coarse landings data to fine scale species distribution.** Annual meeting of the GdR \`Ecology and statistics'. April 2022, Montpellier, France. <a href=ressource/pdf/gdrecostat_2022_alglave.pdf>link</a>

Alglave Baptiste, Vermard Youen, Etienne Marie-Pierre, Woillez Mathieu, Rivot Etienne (2021). **Can we trust commercial landings data to identify essential habitats of harvested fish? Application to several demersal species in the Bay of Biscay.** ISOBAY 17 - XVII International Symposium on Oceanography of the Bay of Biscay. June 2021, virtual event. <a href=ressource/pdf/isobay_2021_alglave.pdf>link</a>

Alglave Baptiste, Vermard Youen, Etienne Marie-Pierre, Woillez Mathieu, Rivot Etienne (2021). **Can we identify fish essential habitats with landings data? Application to the common sole of the Bay of Biscay.** Ecostat 2021: annual meeting of the GdR \`Ecology and statistics'. April 2021, virtual event. <a href=ressource/pdf/gdrecostat_2021_alglave.pdf>link</a>

Alglave Baptiste, Etienne Marie-Pierre, Vermard Youen, Woillez Mathieu, Rivot Etienne (2020). **Spatio-temporal modeling of fishery functional zones by combining catch declarations data and scientific survey data.** Annual meeting of the GdR \`Ecology and statistics'. March 2020, Rennes, France. <a href=ressource/pdf/gdrecostat_2020_alglave.pdf>link</a>

Alglave Baptiste, Lehuta Sigrid, Leforestier Sophie, Vermard Youen (2019). **Management Strategy Evaluation of the Eastern English Channel common sole: management approach under uncertainty.** 14th conference of the AFH \`Fisheries research and sustainable development'. June 2019 , University of Caen Normandie, France. <a href=ressource/pdf/afh_2020_alglave.pdf>link</a>

## Technical report

Alglave Baptiste, Vermard Youen (2022). Ad-hoc contract for the preparation of STECF EWG 22-01 concerning closure areas to protect juveniles and spawners of all demersal stocks in western Mediterranean Sea.

## Additional reports

Alglave Baptiste (2019). **Management Strategy Evaluation of the Eastern English Channel common sole: management approach under uncertainty.** Master thesis. Institut Agro, Rennes. Specialization in fisheries science and quantitative ecology. <a href=https://archimer.ifremer.fr/doc/00756/86773/>link</a>

## Projects and working groups

**Commitment in the MACCO project**

Identification of the target species and by-catch of the Bay of Biscay mixed fishery and evaluation of alternative management strategies.

*Contribution:* production of monthly species distribution maps for the main targeted and by-caught demersal species of the Bay of Biscay. <a href=https://www.macco.fr/>link</a>

*Head of the project:* Stéphanie Mahévas (Ifremer Nantes).

**EWG 22-01 - West Med closure areas** (2022)

Working group aiming at identifying and evaluating the potential closure areas for the demersal species of the Western Mediterranean Sea.

*Contribution:* production of monthly species distribution maps for key data-poor species of the Bay of Biscay.
