---
title: "Teaching & supervision"
editor: visual
---

## Teaching experience

**Practical work in spatial modelling (Msc)** \hfill (2022)

Institut Agro (Rennes), 4 hours.

Here are some <a href=ressource/pdf/cours_td_sdm_2022.pdf>generalities</a>, <a href=ressource/pdf/td_halieut_inla_2022.pdf>an R-INLA introduction </a> and <a href=ressource/codes/td_halieut_inla.zip>the related codes</a>.

N.b. the codes are partly based on codes provided by Thomas Opitz and Denis Allard during an R-INLA workshop.

**Practical work in statistics for fisheries science (MSc)** \hfill (2020)

Institut Agro (Rennes), 20 hours.

Base of statistics: linear model, variance analysis,

**Practical work in basics of probability theory (BSc)** \hfill (2020)

University of Nantes, 20 hours.

## Student and project supervision

**Master student** \hfill (May - July 2022)

*Subject:* Contributions of the lognormal Poisson model in multivariate analysis analysis in community ecology. <a href=ressource/pdf/stage_M1_2022_fabien.pdf>link</a>

*Student:* Théo Fabien.

*Co-supervision with:* Marie-Pierre Etienne, Thomas Outrequin and Jean-Louis Marchand.

**Master thesis** \hfill (February - August 2021)

*Subject:* Combining commercial and scientific data to infer the space-time distribution of sardine in the Bay of Biscay. <a href=https://archimer.ifremer.fr/doc/00756/86774/>link</a>

*Student:* Florian Quemper.

*Co-supervision with:* Etienne Rivot and Marie-Pierre Etienne.

**Student project (MSc)** \hfill (November 2020 - February 2021)

*Subject:* Investigating the effect of catch reallocation on VMS pings for species distribution model predictions. <a href=ressource/pdf/projet_stat_2022_gtt.pdf>link</a>

*Students:* Chloé Tellier, Juliette Theoleyre, Océane Guitton.

*Co-supervision with:* Marie-Pierre Etienne.
